<?php
return array(
    array(
        'title'=>'常用功能',
        'icon'=>'list',
        'code'=>'home',
        'link'=>'Home/index',
        'submenu'=>array(
            array(
                'title'=>'管理首页',
                'icon'=>'home',
                'link'=>'Home/index',
            ),
            array('title'=>'管理账号',
                  'icon'=>'user-secret',
                  'link'=>'Admin/index',
                  'addon'=>array(
                    'title'=>'增加',
                    'link'=>'Admin/add'
                  ),
            ),
            array('title'=>'News',
                'icon' => 'newspaper-o',
                'link'=>'News/index',
            ),
			array('title'=>'Events',
                'icon' => 'newspaper-o',
                'link'=>'Events/index',
            ),
            array('title'=>'Tutorials',
                'icon' => 'newspaper-o',
                'link'=>'Tutorials/index',
            ),
//          array(
//              'title'=>'网站设置',
//              'icon'=>'search',
//              'link'=>'Setting/index'
//          ),
//          array('title'=>'会员管理',
//              'icon' => 'user',
//              'link'=>'Member/index',
//          ),
//          array('title'=>'交易管理',
//              'icon' => 'shopping-cart',
//              'link'=>'Trade/index',
//          ),
//          array('title'=>'发布管理',
//              'icon' => 'newspaper-o',
//              'link'=>'Info/index',
//          ),
//          array('title'=>'在线客服',
//              'icon' => 'comments',
//              'link'=>'Chat/index',
//          ),
//          array('title'=>'报名管理',
//              'icon' => 'table',
//              'link'=>'Apply/index',
//          ),
//          array('title'=>'问卷管理',
//              'icon' => 'table',
//              'link'=>'Question/qa',
//          ),
            
        ),
    ),
);
