<?php
return array(
    'cn' => array(
        'sms_auth' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_test' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_login' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_loginfail' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_register' => '【海外邦】您的验证码是{$code}，您正在注册成为海外邦用户，感谢您的支持！www.hiwibang.com',
        'sms_activity' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_password' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'sms_profile' => '【海外邦】您的验证码是{$code}，15分钟内输入有效。www.hiwibang.com.',
        'mail_auth_title' => '【海外邦】认证验证',
        'mail_auth_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_login_title' => '【海外邦】登录验证',
        'mail_login_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_loginfail_title' => '【海外邦】登录失败',
        'mail_loginfail_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_register_title' => '【海外邦】注册验证',
        'mail_register_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_activity_title' => '【海外邦】发布活动验证',
        'mail_activity_body'=> '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_password_title' => '【海外邦】找回密码验证',
        'mail_password_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
        'mail_profile_title' => '【海外邦】修改资料验证',
        'mail_profile_body' => '您的验证码为 {$code}，海外邦 www.hiwibang.com',
    ),
    'en' => array(
        'sms_auth' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_test' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_login' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_loginfail' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_register' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_activity' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_password' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'sms_profile' => '【HiWiBang】Your verification code is {$code}. Welcome to www.HiWiBang.com',
        'mail_auth_title' => '[HiWiBANG] Verify',
        'mail_auth_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_login_title' => '[HiWiBANG] Login',
        'mail_login_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_loginfail_title' => '[HiWiBANG] Login Failed',
        'mail_loginfail_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_register_title' => '[HiWiBANG] Register',
        'mail_register_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_activity_title' => '[HiWiBANG] Publish',
        'mail_activity_body'=> 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_password_title' => '[HiWiBANG] Forget password',
        'mail_password_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
        'mail_profile_title' => '[HiWiBANG] Modify profile',
        'mail_profile_body' => 'Your verification code is {$code}. HiWiBANG www.hiwibang.com',
    )
);